spring.application.name=backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tak9market?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234

#DDL ??? DB? ?? ??? ?? ??
spring.jpa.hibernate.ddl-auto=update

#true ?? ? jpa ??? ?? ??
spring.jpa.show-sql=true

# JPA? ???? Hibernate? ????? ??? SQL? ???? ???
spring.jpa.properties.hibernate.format_sql=true